default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 20101992

development:
  <<: *default
  database: pro_app_development

test:
  <<: *default
  database: pro_app_test

production:
  <<: *default
  database: pro_app_production
  username: pro_app
  password: <%= ENV['PRO_APP_DATABASE_PASSWORD'] %>
