common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  username: root
  password: 20101992

development:
  <<: *common
  database: pro_app_development

test:
  <<: *common
  database: pro_app_test

staging:
  <<: *common
  database: pro_app_staging

production:
  <<: *common
  database: pro_app
